//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugCaculator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrugCaculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 计算结果：{0} 的本地化字符串。
        /// </summary>
        internal static string CalculateService_CalculateResult_ {
            get {
                return ResourceManager.GetString("CalculateService_CalculateResult_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算 DrugId 为 {0} 的结果 的本地化字符串。
        /// </summary>
        internal static string CalculateService_CalculateResult_计算_DrugId_为__0__的结果 {
            get {
                return ResourceManager.GetString("CalculateService_CalculateResult_计算_DrugId_为__0__的结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件不满足，跳过 DrugId 为 {0} 的规则 的本地化字符串。
        /// </summary>
        internal static string CalculateService_CalculateRules_ {
            get {
                return ResourceManager.GetString("CalculateService_CalculateRules_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始执行 CalculateRules 方法 的本地化字符串。
        /// </summary>
        internal static string CalculateService_CalculateRules_开始执行_CalculateRules_方法 {
            get {
                return ResourceManager.GetString("CalculateService_CalculateRules_开始执行_CalculateRules_方法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在评估 DrugId 为 {0} 的规则 的本地化字符串。
        /// </summary>
        internal static string CalculateService_CalculateRules_正在评估_DrugId_为__0__的规则 {
            get {
                return ResourceManager.GetString("CalculateService_CalculateRules_正在评估_DrugId_为__0__的规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有符合条件的规则 的本地化字符串。
        /// </summary>
        internal static string CalculateService_CalculateRules_没有符合条件的规则 {
            get {
                return ResourceManager.GetString("CalculateService_CalculateRules_没有符合条件的规则", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换后的年龄：{0} {1} 的本地化字符串。
        /// </summary>
        internal static string CalculateService_ConvertAgeToTargetUnit_ {
            get {
                return ResourceManager.GetString("CalculateService_ConvertAgeToTargetUnit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将年龄从 {0} 转换为 {1} 的本地化字符串。
        /// </summary>
        internal static string CalculateService_ConvertAgeToTargetUnit_将年龄从__0__转换为__1_ {
            get {
                return ResourceManager.GetString("CalculateService_ConvertAgeToTargetUnit_将年龄从__0__转换为__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件评估结果：{0} 的本地化字符串。
        /// </summary>
        internal static string CalculateService_EvaluateCondition_ {
            get {
                return ResourceManager.GetString("CalculateService_EvaluateCondition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定的年龄单位：{0} 的本地化字符串。
        /// </summary>
        internal static string CalculateService_GetAgeUnitFromCondition_ {
            get {
                return ResourceManager.GetString("CalculateService_GetAgeUnitFromCondition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最终解析后的条件：{0} 的本地化字符串。
        /// </summary>
        internal static string CalculateService_ParseCondition_ {
            get {
                return ResourceManager.GetString("CalculateService_ParseCondition_", resourceCulture);
            }
        }
    }
}
